// Generated by FlutterFire CLI for project closemap-app.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static bool get isPlaceholder => false;

  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpLOTXvd75Hzvvws3EkDRwf4XK8q_6rTg',
    appId: '1:91046174790:android:0e8def9709eae18b052a47',
    messagingSenderId: '91046174790',
    projectId: 'closemap-app',
    storageBucket: 'closemap-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFXfi2CQ6juyfGU9ubGa_o2xBjcLBjvQ',
    appId: '1:91046174790:ios:6da0d49d7cef20f4052a47',
    messagingSenderId: '91046174790',
    projectId: 'closemap-app',
    storageBucket: 'closemap-app.firebasestorage.app',
    iosBundleId: 'com.closemap.closemap',
  );
}
